name: Run Tests

on: [push, pull_request]

jobs:
  questao1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'


    - name: Run test
      run: |
        python -m unittest tests/test_questao1.py

  questao2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run test
      run: |
        python -m unittest tests/test_questao2.py